version: '3.7'

services:
  postgresdb:
    image: postgis:13.4
    build:
      context: .
      dockerfile: Dockerfile.postgis
    container_name: postgresdb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "--quiet", "--dbname", "${DB_NAME}", "--username", "${DB_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 5
    command: >
      -c max_connections=200
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
      -c work_mem=5242kB
      -c maintenance_work_mem=256MB
      -c min_wal_size=1GB
      -c max_wal_size=2GB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100

volumes:
  postgres-data:
