default: &default
  adapter: postgis
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host:     <%= ENV.fetch('DB_HOST') { Rails.application.credentials.dig(Rails.env.to_sym, :db, :host) } %>
  username: <%= ENV.fetch('DB_USER') { Rails.application.credentials.dig(Rails.env.to_sym, :db, :user) } %>
  password: <%= ENV.fetch('DB_PASS') { Rails.application.credentials.dig(Rails.env.to_sym, :db, :pass) } %>
  port:     <%= ENV.fetch('DB_PORT') { Rails.application.credentials.dig(Rails.env.to_sym, :db, :port) } %>
  schema_search_path: public

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { Rails.application.credentials.dig(Rails.env.to_sym, :db, :name) } %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_TEST') { Rails.application.credentials.dig(Rails.env.to_sym, :db, :name) } %>

production:
  <<: *default
